# Generated by Django 6.0.3 on 2026-03-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='hello_user',
        ),
    ]
